### ISSUE TITLE
Training Script present in the Repo doesn't work

### ISSUE THREAD

**Issue by Nikzy7** [parshnt/rock-paper-scissor#1]
The training script for the mobilenet v2 model is not working properly. I guess the scipt was designed for a 2 class classification. However, you are using 4 classes.

**Comment by parshnt** [comment]
yes, @Nikzy7,

I wasn't able to modify the script for 4 classes, go ahead and make the apt changes.

**Comment by Nikzy7** [comment]
Did That ! 4 classes now work fine... however the dataset is not good... accuracy was nearing 100% probably need to work on the dataset
